name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # Install minimal dependencies for pylint analysis
        if [ -f requirements-ci.txt ]; then 
          pip install -r requirements-ci.txt || echo "CI requirements failed, continuing without extra dependencies"
        fi
    - name: Analysing the code with pylint
      run: |
        # Run pylint with error tolerance for missing optional dependencies
        pylint $(git ls-files '*.py') --exit-zero || echo "Pylint completed with warnings"
