name: Self-Improvement with Copilot

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  self_improvement:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Try CI requirements first, with timeout and fallback
          timeout 300 pip install -r requirements-ci.txt || \
            echo "CI requirements failed or timed out"
          # Install individual critical dependencies
          timeout 120 pip install requests python-dotenv || \
            echo "Individual installs failed"

      - name: Run Copilot suggestions script
        run: |
          python copilot_suggestions.py
